


// AUTHENTICATION START

export const CREATE_USER = 'CREATE_USER';
export const LOGIN = 'LOGIN';
export const LOGOUT= 'LOGOUT';

// AUTHENTICATION END





// LOADING, MESSAGES, CLEAR MESSAGE AND ERROR START

export const LOADING = 'LOADING';
export const ERROR = 'ERROR';
export const MESSAGE = 'MESSAGE';
export const CLEAR = 'CLEAR';
export const CLEARMESSAGE = 'CLEARMESSAGE';

// LOADING, MESSAGES, CLEAR MESSAGE AND ERROR END




// ADDING PRODUCTS START

export const ADD_PRODUCTS = 'ADD_PRODUCTS';

// ADDING PRODUCTS END



// UPDATING PROFILE START
export const UPDATE_PROFILE= 'UPDATE_PROFILE';


// UPDATING PROFILE END




// GETTIN USER START

export const GET_USER = 'GET_USER';

// GETTING USER END
