


// AUTHENTICATION START

export const CREATE_USER = 'CREATE_USER';
export const LOGIN = 'LOGIN';
export const LOGOUT= 'LOGOUT';

// AUTHENTICATION END





// LOADING, MESSAGES, CLEAR MESSAGE AND ERROR START

export const LOADING = 'LOADING';
export const ERROR = 'ERROR';
export const MESSAGE = 'MESSAGE';
export const CLEAR = 'CLEAR';
export const CLEARMESSAGE = 'CLEARMESSAGE';

// LOADING, MESSAGES, CLEAR MESSAGE AND ERROR END




// ADDING PRODUCTS START

export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const GET_ONE_PRODUCT = 'GET_ONE_PRODUCT';


// ADDING PRODUCTS END



// UPDATING PROFILE START
export const UPDATE_PROFILE= 'UPDATE_PROFILE';


// UPDATING PROFILE END




// GETTIN USER START, Products

export const GET_USER = 'GET_USER';
export const GET_PRODUCT = 'GET_PRODUCT';

// GETTING USER END




// EVERYTHING THAT HAS TO DO WITH CART START

export const ADD_TO_CART = 'ADD_TO_CART';
export const GET_CART = 'GET_CART'
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM'
export const UPDATE_CART = 'UPDATE_CART'
export const INCREASE_QTY = 'INCREASE_QTY '
export const DECREASE_QTY = 'DECREASE_QTY'
export const FINISH_ORDER = 'FINISH_ORDER'
export const ACTIVE = 'ACTIVE'
export const CLEAR_CART = 'CLEAR_CART'
export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM'

// EVERYTHING THAT HAS TO DO WITH CART END


// EVERYTHING THAT HAS TO DO WITH ORDER START


export const GET_ORDER = 'GET_ORDER'
export const CREATE_ORDER = 'CREATE_ORDER'

// EVERYTHING THAT HAS TO DO WITH ORDER END
